const router = require('express').Router();
const auth = require('../middleware/authMiddleware');
const upload = require('../middleware/uploadMiddleware');
const c = require('../controllers/storyController');

// ─── Core ─────────────────────────────────────────────────────────────────
router.post('/', auth, upload.single('media'), c.createStory);
router.post('/voice', auth, upload.single('voice'), c.createVoiceStory);
router.get('/feed', auth, c.getFeedStories);
router.get('/archive', auth, c.getArchive);
router.post('/archive/:id', auth, c.archiveStory);
router.get('/highlights', auth, c.getHighlights);
router.get('/highlights/:userId', auth, c.getHighlights);
router.post('/highlights', auth, c.createHighlight);
router.put('/highlights/:id', auth, c.updateHighlight);
router.delete('/highlights/:id', auth, c.deleteHighlight);
router.get('/explore', auth, c.getExplore);
router.get('/memories', auth, c.getMemories);
router.get('/map', auth, c.getStoryMap);
router.get('/nexus-now', auth, c.getNexusNow);
router.get('/featured', auth, c.getFeaturedStories);
router.post('/featured/:id', auth, c.featureStory);
router.delete('/featured/:id', auth, c.unfeatureStory);
router.get('/campus', auth, c.getCampusStories);
router.get('/campus/:tag', auth, c.getCampusStories);
router.get('/course/:code', auth, c.getCourseStories);
router.get('/batch/:batch', auth, c.getBatchStories);
router.get('/department/:dept', auth, c.getDepartmentStories);
router.get('/event/:eventId', auth, c.getEventStories);
router.post('/event/:eventId', auth, upload.single('media'), c.addEventStory);
router.post('/collab', auth, c.createCollaborativeStory);
router.get('/collab/:id', auth, c.getCollaborativeStories);
router.post('/collab/:id/join', auth, c.joinCollaborativeStory);
router.get('/group/:groupId', auth, c.getGroupStories);
router.get('/channel/:channelId', auth, c.getChannelStories);
router.post('/ai/suggest', auth, c.aiSuggestStory);
router.get('/:id/viewers', auth, c.getViewers);
router.get('/:id/reactions', auth, c.getReactions);
router.post('/:id/react', auth, c.reactStory);
router.get('/:id/replies', auth, c.getReplies);
router.post('/:id/reply', auth, c.replyStory);
router.delete('/:id/replies/:rid', auth, c.deleteReply);
router.post('/:id/share', auth, c.shareStory);
router.post('/:id/translate', auth, c.translateStory);
router.post('/:id/quiz', auth, c.submitQuiz);
router.post('/:id/poll', auth, c.votePoll);
router.get('/:id/poll', auth, c.getPollResults);
router.get('/:id/analytics', auth, c.getAnalytics);
router.post('/:id/view', auth, c.viewStory);
router.delete('/:id', auth, c.deleteStory);
router.put('/:id', auth, c.updateStory);

module.exports = router;
